KafkaServer {
  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
  clientId="manish_client"
  clientSecret="xmKRuDdkOWV1RLF30LuFOkyBV6gKFJsunF98FYHSUvqEqsJASjVReZdSc09bEh6ep51ccFBPcPiYabYUq4q23w"
  sasl.oauthbearer.token.endpoint.url="http://host.docker.internal:8080/realms/master/protocol/openid-connect/token"
  sasl.oauthbearer.jwks.endpoint.url="http://host.docker.internal:8080/realms/master/protocol/openid-connect/certs"
  sasl.oauthbearer.username.claim="preferred_username";
};

KafkaClient {
  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
  oauth.token.endpoint.uri="http://keycloak:8080/realms/master/protocol/openid-connect/token"
  oauth.client.id="manish_client"
  oauth.client.secret="xmKRuDdkOWV1RLF30LuFOkyBV6gKFJsunF98FYHSUvqEqsJASjVReZdSc09bEh6ep51ccFBPcPiYabYUq4q23w"
  oauth.jwks.endpoint.uri="http://keycloak:8080/realms/master/protocol/openid-connect/certs"
  oauth.valid.issuer.uri="http://keycloak:8080/realms/master"
  oauth.username.claim="preferred_username";
};
